### ISSUE TITLE
EfficientNetB0 compiler Model not quantized

### ISSUE THREAD

**Issue by LINYOUWEI0804** [google-coral/edgetpu#213] opened 2020-09-01 05:25 UTC
I use EfficientNetB0 in jupyter notebook to transfer learning.Then use tensorflow to train and quantize to convert to INT8.
After the quantization is completed, the compilation starts, but there is no quantization problem.

My Version: ubuntu 18.04
                         Edge TPU Compiler version 14.1.317412892
                         python 3.6
                         tf-nightly-gpu           2.4.0.dev20200811
                         Keras                    2.3.1

My model: https://drive.google.com/file/d/1dceGKCTualI7f-JWMV5Zj-DeAhNq_xM7/view?usp=sharing
My code:
[Mycode.zip](https://github.com/google-coral/edgetpu/files/5154088/Mycode.zip)

error:
must@must-HP-Z440-Workstation:~/下載/generater/model/save_model/efficientnet$ edgetpu_compiler 224_io.tflite
Edge TPU Compiler version 14.1.317412892
Invalid model: 224_io.tflite
Model not quantized

**Comment by Namburger** [comment] 2020-09-01 14:50
@LINYOUWEI0804 Hi!
Can you try adding this line? 
```
converter.optimizations = [tf.lite.Optimize.DEFAULT]
```
that should force the tflite converter to apply quantization and fails if it's unable to

**Comment by Namburger** [comment] 2020-09-01 15:05
If that doesn't work out, could you try the official tensorflow efficientnet instead?
https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet/edgetpu

**Comment by LINYOUWEI0804** [comment] 2020-09-02 03:15
Thanks for your reply!
I have this line already in line 36 of the program.

The official tensorflow efficientnet seems to be the teaching of Cloud TPUs, but I run it on jupyter notebook

**Comment by Namburger** [comment] 2020-09-02 14:22
@LINYOUWEI0804 Hi again!
I see, sorry I didn't catch that, I think it's because it's in a separate cell!
I know that previously the efficientnet-edgetpu models were released with tf1.15.3, I'm not 100% sure how different it is when you use tf2.x. However, there is one thing that could definitely cause this issue, see with keras from tensorflow2.x, the batchsize is not set by default, you can see it in the model summary: `(None, 224, 224, 3)`

Could you try setting the batchsize to 1 before quantizing it?
```
model.input.set_shape((1,) + model.input.shape[1:])
model.input.shape
converter = tf.lite.TFLiteConverter.from_keras_model(model)
```

**Comment by Namburger** [comment] 2020-09-02 17:38
@LINYOUWEI0804 okay, had a little time today so I reproduced this notebook which is very similar to yours minus a few extra parameters you had that I didn't look into. Model evaluation and compiled just fine with the fix I mentioned above, you can follow this to customize your model:
https://colab.research.google.com/drive/1TicOJZGtt-oqmxmo84Dn8HKrwdwJiada?usp=sharing

Cheers

**Closed by Namburger** 2020-09-02 17:38 UTC
Labels: compiler

**Comment by LINYOUWEI0804** [comment] 2020-09-03 03:52
According to the notebook quantitative model, it can be successfully compiled as a result, thank you very much for your help!!

**Comment by Namburger** [comment] 2020-09-03 11:33
No problems!

**Comment by LINYOUWEI0804** [comment] 2020-11-02 03:33
Hello, this is the model I recently trained. After quantification, the size should be 1/4 smaller, but mine is 1/10 smaller. Is this normal?

![h5大小](https://user-images.githubusercontent.com/58504153/97827394-26e96400-1cff-11eb-9eb9-0b646cd71a91.png)

![tflite](https://user-images.githubusercontent.com/58504153/97827384-1fc25600-1cff-11eb-8513-b684f323fb21.png)
