### ISSUE TITLE
EDGETPU_COMPILER: Didn't find op for builtin opcode 'RELU' version '2'

### ISSUE THREAD

**Issue by gasgallo** [google-coral/edgetpu#34] opened 2019-12-19 10:03 UTC
Hi,

I'm having some trouble in compiling my tflite model for edgetpu. I get the following error when calling ` edgetpu_compiler models/model.tflite`:
```
Edge TPU Compiler version 2.0.267685300
ERROR: Didn't find op for builtin opcode 'RELU' version '2'

ERROR: Registration failed.

Invalid model: models/model.tflite
Model could not be parsed
```
But from https://coral.ai/docs/edgetpu/models-intro/#supported-operations I was expecting ReLU to be supported.

P.S. I've converted my TF model to full-integer post-training quantized tflite model with the following code:
```
import os

import tensorflow as tf
import numpy as np
from PIL import Image


model = 'model'
input_size = 112

dataset = []
directory_images = './models/' + model + '/data_test'
directory_saved = './models/' + model
for img in os.listdir(directory_images):
	data = Image.open(os.path.join(directory_images,img)).resize((input_size, input_size))
	data = np.asarray(data, dtype=np.float32)[np.newaxis, :]
	dataset.append(data)

def representative_dataset_gen():
    for input_value in tuple(dataset):
        yield [input_value]

converter = tf.lite.TFLiteConverter.from_saved_model(directory_saved + "/saved")
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

tflite_model = converter.convert()

name = directory_saved + "/" + model
open(name + ".tflite", "wb").write(tflite_model)
```

**Comment by Namburger** [comment] 2019-12-19 12:18
@gasgallo could you attach you model?

**Comment by gasgallo** [comment] 2019-12-20 02:58
@Namburger sure, you can get it from [here](https://drive.google.com/file/d/1v2zNcwlkDuvvxfB1OYxoHrEM8As3pq-C/view?usp=sharing)

**Comment by Namburger** [comment] 2019-12-20 15:35
@gasgallo What tensorflow version are you using to train and convert? 
I ran the [visualized tool](https://www.tensorflow.org/lite/guide/faq#model_conversion) and see that the tflite_tool was able to convert most of your ops except for a couple of float32 ops. This is most likely the cause of the crash. 
However this is fixed internally so this model will be compiled just fine once we release the new version of the compiler. If you are using tf2.0, I suggest downgrading to tf1.15. 

Here is the output of visualized.py, for you info:
https://gofile.io/?c=ats6gA

**Comment by gasgallo** [comment] 2019-12-21 00:51
@Namburger thanks for the help! I'm already using tf 1.15.0.

Im very surprised to hear that some ops are still in float32, especially because I wasn't expecting so when using 'converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]' when converting. Isn't it supposed to throw an error if any op isn't supported in int8?

Other than that, is there anything I can do to  ompile and run my model before you guys release the new version of the compiler?

**Comment by Namburger** [comment] 2019-12-23 15:16
@gasgallo post training quantization is a [little limited](https://www.tensorflow.org/lite/performance/post_training_quantization#full_integer_quantization_of_weights_and_activations), some ops maybe not be quantized even when you did everything right. This is why we recommend quantization aware training.

**Comment by gasgallo** [comment] 2019-12-24 02:36
Ok, I'll give quantization-aware training a try then and let you guys know.

**Closed** 2019-12-24 02:36 UTC
