### ISSUE TITLE
Memory leak when edgetpu run in thread

### ISSUE THREAD

**Issue by Drulludanni** [google-coral/edgetpu#566] opened 2022-03-28 14:28 UTC
### Description

Hi, I'm running into a memory leak when the edgetpu is runs in a thread.

    from threading import Thread
    import cv2
    import numpy as np
    from pycoral.utils import edgetpu
    model = edgetpu.make_interpreter(model_path)

    def find_points(frame):
        image_size_for_model = (256, 256)
        scale = np.shape(frame)[:2]/np.array(image_size_for_model)
        frame = cv2.resize(frame, image_size_for_model)
        frame = np.expand_dims(frame, axis=0)

        common.set_input(model, frame)
        model.invoke()
        pred = common.output_tensor(model, 0)
        points, confidence = find_points_from_pred(pred[0]) #just some numpy calls
        return points, confidence
        
    class Memleak_test:
        def __init__(self):
            self.thread = None

        def pred(self, color):
            find_points(color)

        def run_threaded(self, color):
            self.thread = Thread(target=self.pred, args=(color,))
            self.thread.start()

        def test_memleak(self):
            i = 0
            while True:
                print(i)
                i += 1
                if self.thread is not None:
                    self.thread.join()
                frame = np.zeros((848, 480, 3)).astype(np.uint8)
                self.run_threaded(frame)

    m = Memleak_test()
    m.test_memleak()
    
The final function in the while loop can either be `run_threaded` or `pred`, if it is `pred` then there is no leak but if it is `run_threaded` it leaks about 1 Mb every 1000 iterations, it does so on both windows and linux, however it seems to leak significantly slower on windows, I've tried running both with pci and usb and both seem to leak.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Windows 10, Linux

### Coral Device

USB Accelerator, Mini PCIe

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment] 2022-03-29 02:47
issue seems to be similar to this issue : https://stackoverflow.com/questions/53348644/python-threads-memory-leak

can you try to del frame and see whether it solves the issue or not. Thanks!

```
 if self.thread is not None:
     self.thread.join()
     del frame
```

**Comment by Drulludanni** [comment] 2022-03-29 09:34
no, it seems that calling `del frame` does not solve the issue

**Comment by hjonnala** [comment] 2022-03-29 13:04
okay, can you please share how you are calculating the memory leak on linux? Thanks!

**Comment by Drulludanni** [comment] 2022-03-29 14:52
I just watch the amount of reserved memory go up in htop, program usually starts at around 80 MB then in an hour it is at around 150 MB, I left it running over the weekend and the memory footprint was at 4GB when I came back monday morning so it is definitely not just random fluctuations.

**Comment by hjonnala** [comment] 2022-06-20 13:58
Closing the issue as the underlying problem is not relevant to Coral Specific. Here's the reproducible code without any Coral specific calls.

```
import threading
import cv2
import numpy as np
import psutil
import os
import gc
import tracemalloc
import sys
import time

tracemalloc.start()

def find_points(frame):
    image_size_for_model = (224, 224)
    scale = np.shape(frame)[:2] / np.array(image_size_for_model)
    frame = cv2.resize(frame, image_size_for_model)
    frame = np.expand_dims(frame, axis=0)

class Memleak_test:
    def __init__(self):
        self.thread = None

    def pred(self, color):
        find_points(color)

    def run_threaded(self, color):
        self.thread = threading.Thread(target=self.pred, args=(color,))
        self.thread.start()


    def test_memleak(self):
        if self.thread is not None:
            self.thread.join()
            # threading.shutdown()
        frame = np.zeros((848, 480, 3)).astype(np.uint8)
        self.run_threaded(frame)
        print(psutil.Process(os.getpid()).memory_info())

        return None


m = Memleak_test()
while True:
    m.test_memleak()
```

**Closed as completed by hjonnala** 2022-06-20 13:58 UTC
Labels: type:bug, subtype:windows, subtype:ubuntu/linux, Hardware:USB Accelerator, Hardware:Mini PCIe, comp:model
