### ISSUE TITLE
ERROR std::out_of_range: vector when compiling working tflite model

### ISSUE THREAD

**Issue by DocDriven** [google-coral/edgetpu#4] opened 2019-10-01 09:35 UTC
I am trying to convert a working tflite model with edgetpu_compiler version 2.0.267685300. The compilation terminates unsuccessfully with some console output:

```
Edge TPU Compiler version 2.0.267685300
terminating with uncaught exception of type std::out_of_range: vector

Internal compiler error. Aborting!
```
The tflite model was created by using the tensorflow nightly docker image. The code to reproduce the error can be found on my repo: [test code](https://github.com/DocDriven/tflite_tests). Just execute the commands in order

```
python keras_model.py
python keras_conversion.py
```
I'm afraid I cannot debug this, as I am unable to find the source code for the compiler. If I can contribute anything to resolve this issue, let me know.

**Comment by manoj7410** [comment] 2019-10-02 07:10
Please make sure your input model is a fully quantized tflite model. You can use tensorflow/lite/tools/visualize.py to check the tensors of your tflite model. For a fully quantized model, most of the tensors should be marked as uint8 / int8 type. All tensors, including activation tensors and parameter tensors should be of type uint8 / int8. Also, please make sure your model is not too big, <100M for now.

**Comment by DocDriven** [comment] 2019-10-02 07:59
@manoj7410 
Thanks for your response. I have double checked my model with the visualize.py script and added the html file to my repository. Almost all nodes are of type uint8 / int8, except for MatMul nodes of Dense layers, which are of type int32.

I did utilize full integer post-training quantization, which is - according to the coral website - supported. Also, the model size is nowhere near that number (13K for that particular model).

Do you have any other points which could be problematic?

**Comment by DocDriven** [comment] 2019-10-02 11:32
@manoj7410 
I have tracked down the problem, and it seems the following function causes the compilation to fail:

`tf.random.normal(shape=(10,), mean=0, stddev=1, dtype=tf.float32)`

After removing this line and inserting some dummy values instead, the compilation works. Is there a solution or workaround to this problem?

**Comment by Namburger** [comment] 2019-10-03 20:35
hi @DocDriven, Nam from Coral team here - 
Thanks for submitting the issue. We were able to reproduce your exact issue as reported. We are working on the next release which will fix this problem. I'll keep you updated.

**Comment by mpariente** [comment] 2019-12-27 17:20
How about feeding epsilon ([here](https://github.com/DocDriven/tflite_tests/blob/master/keras_model.py#L29)) to the model as an input? 
This should work right?

**Comment by Namburger** [comment] 2020-05-11 20:04
It's been too long, but this compiles now :)
```
edgetpu_compiler -s vae_keras.tflite
Edge TPU Compiler version 2.1.302470888

Model compiled successfully in 14 ms.

Input model: vae_keras.tflite
Input size: 12.61KiB
Output model: vae_keras_edgetpu.tflite
Output size: 52.49KiB
On-chip memory used for caching model parameters: 18.00KiB
On-chip memory remaining for caching model parameters: 8.00MiB
Off-chip memory used for streaming uncached model parameters: 64.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 10
Operation log: vae_keras_edgetpu.log

Operator                       Count      Status

LOGISTIC                       1          Mapped to Edge TPU
ADD                            1          Mapped to Edge TPU
FULLY_CONNECTED                5          Mapped to Edge TPU
MUL                            1          Mapped to Edge TPU
QUANTIZE                       2          Mapped to Edge TPU
```

**Closed by Namburger** 2020-05-11 20:04 UTC

**Comment by keesschollaart81** [comment] 2020-09-29 06:50
I want to make a note that the edgetpu compiler can be a bit flaky/indeterministic. For others reading this, trying a few times might 'fix' this... In my case, sometimes it gives the 'vector' errors, sometimes just the 'internal compiler error' and sometimes it just works:

![image](https://user-images.githubusercontent.com/6755359/94522795-7df7a700-0230-11eb-9648-50ac849d25ca.png)

**Comment by Namburger** [comment] 2020-09-29 11:38
@keesschollaart81 this could be due to a memory allocator that is flaky in the compiler, we've fixed this and expecting this to be released by mid q4. 
Would you be able to submit your model? I would like to try compiling it again from our head

**Comment by keesschollaart81** [comment] 2020-09-29 11:40
Sure, model attached, based on [this config](https://github.com/tensorflow/models/blob/master/research/object_detection/configs/tf2/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8.config). 

[model.zip](https://github.com/google-coral/edgetpu/files/5298663/model.zip)

**Comment by Namburger** [comment] 2020-09-29 15:11
@keesschollaart81 can confirm this is no longer an issue!
