### ISSUE TITLE
edgetpu-deeplab compile error

### ISSUE THREAD

**Issue by Aspirinkb** [google-coral/edgetpu#315] opened 2021-02-14 03:45 UTC
After `edgetpu-deeplab` model trained on my customer dataset which has only two class, I convert the frozen model to tflite format. When I compile the frozen tflite model using edgetpu_compiler, it runs forever and return nothing on the terminal except '_Edge TPU Compiler version 15.0.340273435'_.

convert command:
```
tflite_convert \
--graph_def_file=./frozen_inference_graph_quant.pb \
--output_file=./edgetpu_deeplab_quant.tflite \
--output_format=TFLITE \
--input_shape=1,361,,361 \
--inference_type=QUANTIZED_UINT8 \
--inference_input_type=QUANTIZED_UINT8 \
--std_dev_values=128 \
--mean_values=128 \
--change_concat_input_ranges=true \
--input_arrays="MobilenetEdgeTPU/MobilenetEdgeTPU/input" \
--output_arrays="ArgMax"
```

I see that coral.ai provides a semantic segmentation model, deeplab_mnv2, can you tell me how to get a edgetpu-deeplab model running on edge tpu?

**Comment by Aspirinkb** [comment] 2021-02-14 05:54
'Internal compiler error. Aborting!' error returned after running about 2 hours.

**Comment by jake-g** [comment] 2021-03-03 10:41
i am having this issue as well using the quantized deeplab3 tflite model with the 15.0.340273435 edge tpu compiler. tried compiling on multiple ubuntu based systems. I'm also wondering how the coral.ai edgetpu-deeplab model was generated so that I can reproduce it

Specifically, im trying to go thru [these steps](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md), using the `edgetpu-deeplab` model checkpoint described [here](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md) and downloadable [here](http://download.tensorflow.org/models/edgetpu-deeplab_2020_03_09.tar.gz)

I tried the process with both tf2 and tf1 in isolated environments

Ive attached the .tflite model im attempting to compile

[edgetpu-deeplab_quantized_model.tflite.zip](https://github.com/google-coral/edgetpu/files/6079796/edgetpu-deeplab_quantized_model.tflite.zip)

**Comment by jake-g** [comment] 2021-03-09 05:23
so i've been trying to figure this out for a week. I've tried just about every deeplab checkpoint to initialize from. I can confirm that if i take a deeplabv3 .tflite model from the model zoo or edgetpu examples, the compiler DOES work (takes <10s to finish). it is just when i retrain and export my own model/tflite file when i run into issues. Even just re-training to my 3 class problem for 100 steps, then exporting the .pb and converting to tflite results in the edgetpu compiler hang and eventual abort. Perhaps i am doing something wrong with the tflite conversion (im following the deeplab docs and using the checked in code though). I've tried inspecting the graphs for my custom retrained deeplab model versus the example, working ones, but i dont really spot an obvious difference.

I've tried on pc, linux and docker (using nvidia 1080 gpus). Ive tried a few version of tf (tf 1.15 on ubunutu with cuda 10.1 is my default for this). No matter what io try I 'cant get a deeplab variant model to compile for edge tpu use. I can rrun the regular tflite model on my coral dev board, but it is 100x slower than advertised on the cpu (~4 seconds per inference vs ~0.3 sec on tpu). At this point im starting to look at other hardware and pixel wise segmentation models.

Any ideas? Happy to upload the exact code to reproduce my issue. It is farily easy to reproduce, I used the tensorflow/models/research/deeplab train/export/tflite_convert .py code with minor adjustments to retrain for my 3 class problem

Thanks!

**Comment by manoj7410** [comment] 2021-03-09 07:08
@jake-g Are there any compilation logs that you can share ? I tried to compile your model but my laptop got hanged. 
Can you confirm the link to download deeplabv3.tflite which is being compiled by the EdgeTPU compiler ?
EDIT : Which TF version and Runtime version are you currently working with ?

**Comment by jake-g** [comment] 2021-03-10 09:58
Thanks for replying, ill give some more details
* I have `tensorflow-gpu==1.15.0`,  `tf-slim==1.0` the latest edgetpu compiler `version 15.0.340273435`, python `3.7.7`
* My main machine is ubuntu 20 with cuda 10.1 and 2 nvidia gpus, but i've also tried training/quantizing on windows

I can't get my **re-trained** and quantized deeplabv3 model to compile with the edgetpu compiler I get this...after several minutes of hanging and high cpu
```
$ edgetpu_compiler /mnt/z/my_retrained_deeplabv3.tflite
Edge TPU Compiler version 15.0.340273435

Internal compiler error. Aborting!
```

1. I train using the code in [research/deeplab](https://github.com/tensorflow/models/tree/master/research/deeplab). 
* I have my own tfrecords dataset modeled after the benchmark datasets, 
* The dataset has 2 positive classes + 1 background  class
* Train input is 512x512 (default)
* I train with quantization awareness enabled (per [deeplab quantization](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md))
* Model converges in ~10k steps and performs well using evaluation code
* I have tried the `model_varients`:    'mobilenet_v2' and  'mobilenet_edgetpu'
* also tried starting from scratch or from a checkpoint such as 'EdgeTPU-DeepLab' or 'mobilenetv2_dm05_coco_voc_trainaug' found in the [deeplab model zoo](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md)

2. To export the model checkpoint to `.pb` i use `export_model.py`
3. I convert the `.pb` to `.tflite` using `convert_to_tflite.py` with flags: 
* `--input_tensor_name=MobilenetEdgeTPU/MobilenetEdgeTPU/input:0` (or mobilenet_v2's input if using that varient)
* `--output_tensor_name=ResizeBilinear_2:0` (also tried `ArgMax:0` not totally sure what to use here)
4. I try to compile the `.tflite` model with edgetpu compiler and it hangs for a while and aborts

I can successfully compile **pre-existing** deeplab v3 `.tflite` models, for example: 
* `deeplabv3_mnv2_pascal_quant.tflite` the one included in [`test_data/`](https://github.com/google-coral/edgetpu/tree/master/test_data) 
* `mobilenetv2_dm05_coco_voc_trainaug_8bit` from [deeplab quantize instructions](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md) 
 
I see the following stdout:
```
$ edgetpu_compiler /mnt/z/deeplabv3_mnv2_dm05_pascal_train_aug_8bit.tflite
Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 542 ms.

Input model: /mnt/z/deeplabv3_mnv2_dm05_pascal_train_aug_8bit.tflite
Input size: 733.49KiB
Output model: deeplabv3_mnv2_dm05_pascal_train_aug_8bit_edgetpu.tflite
Output size: 1.06MiB
On-chip memory used for caching model parameters: 805.00KiB
On-chip memory remaining for caching model parameters: 5.98MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 71
Operation log: deeplabv3_mnv2_dm05_pascal_train_aug_8bit_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 64
Number of operations that will run on CPU: 7
See the operation log file for individual operation details.
```

I've tried inspecting for differences between the `.tflite` models that work (the one in `test_data/` for example) and the ones that cause the compiler to hang (see my attachment a few posts up for one based on the `mobilenet_edgetpu` deeplab backend), but I dont see anything obvious. 

My guess is my problem is either:
* my tensorflow / tf-slim versions (although I thought i did what was suggested, plus upgrading either caused training issues)
* the way i train / export the quantization aware trained model `.pb` file
* the way i convert the `.pb` to `.tflite`, perhaps grabbing the wrong output node?

**Comment by jake-g** [comment] 2021-03-22 08:59
@Naveen-Dodda any update? this seems to be affecting several people.

**Comment by Naveen-Dodda** [comment] 2021-03-23 18:43
Hello Jake, 

Thanks for sharing details about the steps you have followed. Can you share checkpoints of model you trained on custom dateset. 

Thanks, 
Naveen

**Comment by jake-g** [comment] 2021-03-23 19:14
Sure, in the zip is the checkpoint at 15k quantization training steps along with the .pb and .tflite generated from it. Thanks for getting back to me!

Note the zip is too big to attach so i've included a google drive link
https://drive.google.com/file/d/125TUMvcmeTMtqXLLIuezBiatftc55j5Z/view?usp=sharing

**Comment by Naveen-Dodda** [comment] 2021-03-23 20:17
Thanks Jake,I assume these checkpoints are trained using Tf1.x.  You mentioned you have also trained these models with TF2.x can you share those checkpoints as well.

**Comment by jake-g** [comment] 2021-03-23 21:16
I had issues related to tf.slim and tensorflow.contrib when training with tf2 using the head [deeplab](https://github.com/tensorflow/models/tree/master/research/deeplab) code. I was never actually able to get it training, but  I was able to use tf2 when converting to tflite, but that didnt make a difference in my edgetpu compiler issues. 

Training deeplab with tf2 is another issue, but I gave up on that for now. It seemed like deeplab hasnt been converted to work with tf2

So for now im sticking with tf1, unless there is a way i can use tf2

**Comment by desmoteo** [comment] 2021-03-28 21:58
> Thanks for replying, ill give some more details
> 
> * I have `tensorflow-gpu==1.15.0`,  `tf-slim==1.0` the latest edgetpu compiler `version 15.0.340273435`, python `3.7.7`
> * My main machine is ubuntu 20 with cuda 10.1 and 2 nvidia gpus, but i've also tried training/quantizing on windows
> 
> I can't get my **re-trained** and quantized deeplabv3 model to compile with the edgetpu compiler I get this...after several minutes of hanging and high cpu
> 
> ```
> $ edgetpu_compiler /mnt/z/my_retrained_deeplabv3.tflite
> Edge TPU Compiler version 15.0.340273435
> 
> Internal compiler error. Aborting!
> ```
> 
> 1. I train using the code in [research/deeplab](https://github.com/tensorflow/models/tree/master/research/deeplab).
> 
> * I have my own tfrecords dataset modeled after the benchmark datasets,
> * The dataset has 2 positive classes + 1 background  class
> * Train input is 512x512 (default)
> * I train with quantization awareness enabled (per [deeplab quantization](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md))
> * Model converges in ~10k steps and performs well using evaluation code
> * I have tried the `model_varients`:    'mobilenet_v2' and  'mobilenet_edgetpu'
> * also tried starting from scratch or from a checkpoint such as 'EdgeTPU-DeepLab' or 'mobilenetv2_dm05_coco_voc_trainaug' found in the [deeplab model zoo](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md)
> 
> 1. To export the model checkpoint to `.pb` i use `export_model.py`
> 2. I convert the `.pb` to `.tflite` using `convert_to_tflite.py` with flags:
> 
> * `--input_tensor_name=MobilenetEdgeTPU/MobilenetEdgeTPU/input:0` (or mobilenet_v2's input if using that varient)
> * `--output_tensor_name=ResizeBilinear_2:0` (also tried `ArgMax:0` not totally sure what to use here)
> 
> 1. I try to compile the `.tflite` model with edgetpu compiler and it hangs for a while and aborts
> 
> I can successfully compile **pre-existing** deeplab v3 `.tflite` models, for example:
> 
> * `deeplabv3_mnv2_pascal_quant.tflite` the one included in [`test_data/`](https://github.com/google-coral/edgetpu/tree/master/test_data)
> * `mobilenetv2_dm05_coco_voc_trainaug_8bit` from [deeplab quantize instructions](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md)
> 
> I see the following stdout:
> 
> ```
> $ edgetpu_compiler /mnt/z/deeplabv3_mnv2_dm05_pascal_train_aug_8bit.tflite
> Edge TPU Compiler version 15.0.340273435
> 
> Model compiled successfully in 542 ms.
> 
> Input model: /mnt/z/deeplabv3_mnv2_dm05_pascal_train_aug_8bit.tflite
> Input size: 733.49KiB
> Output model: deeplabv3_mnv2_dm05_pascal_train_aug_8bit_edgetpu.tflite
> Output size: 1.06MiB
> On-chip memory used for caching model parameters: 805.00KiB
> On-chip memory remaining for caching model parameters: 5.98MiB
> Off-chip memory used for streaming uncached model parameters: 0.00B
> Number of Edge TPU subgraphs: 1
> Total number of operations: 71
> Operation log: deeplabv3_mnv2_dm05_pascal_train_aug_8bit_edgetpu.log
> 
> Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
> Number of operations that will run on Edge TPU: 64
> Number of operations that will run on CPU: 7
> See the operation log file for individual operation details.
> ```
> 
> I've tried inspecting for differences between the `.tflite` models that work (the one in `test_data/` for example) and the ones that cause the compiler to hang (see my attachment a few posts up for one based on the `mobilenet_edgetpu` deeplab backend), but I dont see anything obvious.
> 
> My guess is my problem is either:
> 
> * my tensorflow / tf-slim versions (although I thought i did what was suggested, plus upgrading either caused training issues)
> * the way i train / export the quantization aware trained model `.pb` file
> * the way i convert the `.pb` to `.tflite`, perhaps grabbing the wrong output node?

This is exactly what I have been trying and I am getting the same behavior. I have been trying with both tf 1.15.0 and 1.15.3, with more or less the same results.

I tried as well https://colab.research.google.com/github/google-coral/tutorials/blob/master/fix_conversion_issues_ptq_tf2.ipynb#scrollTo=kujXSsDoXxCr  using tf 2.3 to convert to tflite. Tried both tflite_convert and convert_to_tflite.py script with no success

Compiler just changes behavior if flag -n is used to split into segments. In this case it does not hang but dies immediately.

**Comment by Naveen-Dodda** [comment] 2021-04-05 17:09
Hello,

I am trying to export the fozen graph from your checkpoints (model.ckpt-15000 ) but the export fails if i use the default command from here. https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md

can you share the export command you have used for export_model.py .

Thanks

**Comment by jake-g** [comment] 2021-04-06 06:11
I think the only flag in [export_model.py](https://github.com/tensorflow/models/blob/master/research/deeplab/export_model.py) for all the flags that can be supplied) that i changed was `--num_classes=3`, does it work if you supply that?

**Comment by Naveen-Dodda** [comment] 2021-04-06 19:01
It doesn't export.

Can you please take a look at the colab notebook attached and share me back a colab to export the your model with the checkpoints you shared above.
[deep_lab_test.ipynb.zip](https://github.com/google-coral/edgetpu/files/6266982/deep_lab_test.ipynb.zip)

**Comment by jake-g** [comment] 2021-04-07 03:52
thanks for the example. I got it working on my end with a public colab kernel. I had to change two things.

There first is the `model_variant` flag need to be set to the `mobilenet_edgetpu` like so:
```
!python deeplab/export_model.py \
    --checkpoint_path=/content/model.ckpt-15000 \
    --quantize_delay_step=0 \
    --model_variant='mobilenet_edgetpu' \
    --export_path=/content/frozen_inference_graph.pb \
    --num_classes=3
```

Second, and less obvious...ive been using tf.slim 1.0 to train and convert models. The reason was related to deeplab training issues i had with newer tf.slip pip releases. Training and everything worked wine with `tf-slim==1.0` in your colab i simply added the following after all the other compilation and pip install cells are done:
```
!python -m pip install tf-slim==1.0
```


when `export_model.py` works, the final output looks like this:

```
W0407 03:43:45.016468 139655608608640 deprecation.py:323] From /tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
INFO:tensorflow:Froze 585 variables.
I0407 03:43:45.511318 139655608608640 graph_util_impl.py:334] Froze 585 variables.
INFO:tensorflow:Converted 585 variables to const ops.
I0407 03:43:45.618662 139655608608640 graph_util_impl.py:394] Converted 585 variables to const ops.
```

and then for converting to tflite, i ran this in a cell (note the `input_tensor_name` is slightly different than what you had)
```
!python deeplab/convert_to_tflite.py \
  --quantized_graph_def_path=/content/frozen_inference_graph.pb \
  --input_tensor_name=MobilenetEdgeTPU/MobilenetEdgeTPU/input:0 \
  --output_tflite_path=frozen_inference_graph.tflite
```

when this works, then full output is:
```
/content/models/research
2021-04-07 03:44:10.040081: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-04-07 03:44:10.051025: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-04-07 03:44:10.051079: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (22421389b1ea): /proc/driver/nvidia/version does not exist
2021-04-07 03:44:10.056409: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200210000 Hz
2021-04-07 03:44:10.056651: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55b8d67d4840 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-07 03:44:10.056687: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-04-07 03:44:10.107246: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2021-04-07 03:44:10.107545: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2021-04-07 03:44:10.163709: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:786] Optimization results for grappler item: graph_to_optimize
2021-04-07 03:44:10.163782: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   function_optimizer: function_optimizer did nothing. time = 0.008ms.
2021-04-07 03:44:10.163795: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   function_optimizer: function_optimizer did nothing. time = 0ms.
```

**Comment by Naveen-Dodda** [comment] 2021-04-07 22:14
Hello Jake, 

You have mentioned that you have same problem with model type mobilenetv2 as well right.

**Comment by jake-g** [comment] 2021-04-08 00:34
yeah, i repeated the same train/quantize/export steps but trained the regular deeplab moblenetv2 model instead of the edgetpu variant. Although i dont have a checkpoint on hand, it was kind of part of the whirlwind of debugging i did prior to posting this issue.

**Comment by jake-g** [comment] 2021-04-18 20:25
@Naveen-Dodda any ideas for things to try? has anybody been able to re-train deeplab and convert to tpu compatible model?

**Comment by desmoteo** [comment] 2021-04-23 09:19
I finally managed to make it compile if I run training with the same flags and doing post-quantization as reported in #325 . But if I make changes to this configuration, e.g. change the crop size, compilation hangs again (even if the quantized tflite model seems well converged and is producing good results).

**Comment by ghumman3131** [comment] 2021-05-03 05:32
I am also facing same issue ( compiler gives internal error) , I am doing the quantization aware training as mention [here](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md) but fails to convert tflite model using edge tpu compiler. I have downloaded the 8 bit quantized model ([this](http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_train_aug_8bit_2019_04_26.tar.gz)) and when I export frozen graph using model.ckpt from that directory with deeplab/export_model.py and make tflite from the frozen graph , edge tpu compiler fails to convert tflite. But when I generate tflite from the frozen graph which is already in  8 bit quantize model edge tpu compiler works and generate edge tpu model file.

So I think the issue is how we are exporting the inference graph

**Comment by ghumman3131** [comment] 2021-05-03 07:28
I managed to compile deeplab tflite on edgetpu  by doing post quantization and using mobilenet edgetpu as mentioned [here](https://github.com/google-coral/edgetpu/issues/325)

**Comment by ghumman3131** [comment] 2021-05-03 08:53
> I finally managed to make it compile if I run training with the same flags and doing post-quantization as reported in #325 . But if I make changes to this configuration, e.g. change the crop size, compilation hangs again (even if the quantized tflite model seems well converged and is producing good results).

I run the same code with custom crop size and compiler successfully compiles the tflite model

**Closed as completed** 2021-09-01 19:44 UTC
Labels: type:support, comp:compiler, comp:demo
