### ISSUE TITLE
Cannot run sudo apt-get and sudo apt dist-upgrade

### ISSUE THREAD

**Issue by slbejaranom** [google-coral/edgetpu#387] opened 2021-05-18 14:18 UTC
Well this is my issue:

I have a 1gb ram Google Coral which I've been using for a while, I flash it using the bash.sh script in ubuntu and normally thinigs used to go well, however, I reflashed it with a new version of mendel some weeks ago and used

sudo apt-get update

which threw this error in many repositories "TLS Handshake failed" Idk if it has to do with the https in the repositories or idk.

And once it finishes it says that some repos were replaced for old files and will not be updated or couldn't have been gotten.

I'm facing this problem which doesn't either allow me to download libraries nor gcc compiler that I need for my projects.

Any help with this? maybe @Namburger

**Comment by PeterMalkin** [comment] 2021-05-18 16:13
Can you please follow the instructions here: https://coral.ai/docs/accelerator/get-started/#runtime-on-linux

**Comment by slbejaranom** [comment] 2021-05-18 19:07
Does it work the same with the dev board? I've already followeed the tutorial many times

**Comment by manoj7410** [comment] 2021-05-19 11:31
@slbejaranom Did you try to upgrade again? If the issue is still persistent then can you please paste the complete error here ?

**Comment by wwooster** [comment] 2021-05-20 10:24
Maybe your internet connection on the dev-board is not working. Try pinging some web page, I had the same issue.

https://coral.ai/docs/dev-board/get-started/#connect-internet
https://aallan.medium.com/hands-on-with-the-coral-dev-board-adbcc317b6af (Connecting the development board to your wireless network
)

**Comment by manoj7410** [comment] 2021-05-25 03:25
@slbejaranom Is this issue still reproducible at your end ?

**Comment by strubell** [comment] 2021-06-02 17:35
This is still an issue. Please reopen. On a fresh flash of the board, attempting to `apt-get update` results in:
```
GPG error: https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FEEA9169307EA071 NO_PUBKEY 8B57C5C2836F4BEB
E: The repository 'https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease' is not signed.
```
It can be solved using the solution given [here](https://stackoverflow.com/questions/49582490/gpg-error-http-packages-cloud-google-com-apt-expkeysig-3746c208a7317b0f) but it is not fixed on your end nor has the documentation been sufficiently updated. It's not an internet connectivity issue.

The docs pointed to above by @PeterMalkin are insufficient and confusing because: (1) they are for Linux, so if a user is setting up on e.g. mac they are likely to scroll down and follow those instructions instead (which don't include the relevant command) and (2) those instructions describe a command to be run on the host machine, not the device. The documentation should instead be updated e.g. [here](https://coral.ai/docs/dev-board/get-started/#update-mendel), and possibly in other places.

**Comment by manoj7410** [comment] 2021-06-03 03:54
@strubell The original issue was filed for the error : "TLS Handshake failed" which is not reproducible at our end. 
I'll try to reproduce error reported by you and will get back to you on this. 

Assuming that you are working on a Coral Dev Board. Please correct me if I am wrong.

**Comment by strubell** [comment] 2021-06-03 19:44
Ah, my bad! I was pointed here by someone else when I shared my error and assumed it was the same error (since the same solution works). Yes, I'm using a Coral Dev Board.

**Comment by manoj7410** [comment] 2021-06-04 05:31
@strubell No problem. Can you share the detailed steps to reproduce this error ? Which Mendel image are you working with ?

**Comment by strubell** [comment] 2021-06-08 19:22
I am using the latest image in the docs: `enterprise-eagle-flashcard-20210204152958.zip`.

I am able to reproduce the error by [connecting to the device via the serial console (from macos)](https://coral.ai/docs/dev-board/serial-console/#connect-with-macos) and following steps (1), (2), (3), (5) and (6) [here](https://coral.ai/docs/dev-board/get-started/).

**Comment by manoj7410** [comment] 2021-07-12 10:51
@strubell  I was not able to reproduce this issue at my end. 
Are you still facing this issue ?

**Comment by manoj7410** [comment] 2021-08-03 04:32
Closing this as this issue is not reproducible.

**Closed as completed by manoj7410** 2021-08-03 04:32 UTC
